const listaLivros = document.querySelectorAll('.livro')

const title = document.getElementById('title')
const informacoes = document.getElementById('informacoes')
const sinopse = document.getElementById('sinopse')

listaLivros.forEach((livro, i) => {
    livro.addEventListener('click', () => {
        listaLivros.forEach(livro => {
            livro.classList.remove('selecionado')
        })
        
        livro.classList.add('selecionado')
        title.innerHTML = livro.getAttribute('data-nome')

        if(window.innerWidth < 700){
            window.scrollTo({ top: 0 })
        }

        switch (i) {
            case 0:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 432 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 434 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Ela roubou uma vida. Agora deve pagar com o coração.</p><p>Num mundo dividido uma muralha mágica separa duas espécies. De um lado, os feéricos vivem dentro de suas fronteiras cheias de beleza e mistério; do outro, os humanos possuem apenas medo, desconfiança e dificuldades.</p><p>Feyre, filha de um casal de mercadores humanos e falidos, se torna caçadora para sustentar a família. Dura como as flechas que carrega, letal como sua pontaria, ela abandona as fantasias de garota e as troca pela árdua vida nas florestas ao redor de sua aldeia.</p><p>Sua única alegria é observar as cores e sonhar em capturá-las. Mas, na floresta, coberta de neve tudo é branco e árido; como o ódio pelos feéricos que carrega no coração; Como as telas que não pode comprar ou colorir. Até que um enorme lobo cruza seu caminho... Sem hesitar, Feyre dispara... uma flecha. Um ato de rebelião.</p><p>Após matar o lobo, uma criatura bestial surge exigindo uma reparação. Arrastada para além do muro, para uma terra mágica e traiçoeira - que ela só conhece por meio de lendas -, a jovem descobre que seu captor não é um animal, mas Tamlin, Grão Senhor da Terra Primaveril. Um feérico com um segredo, escondido sob uma máscara. Ela descobre ainda que o então animal que havia assassinado era, na verdade, uma criatura mágica, uma fada zoomórfica transformada em lobo.</p><p>À medida que ela descobre mais sobre este mundo onde a magia impera, seus sentimentos por Tamlin passam da mais pura hostilidade até uma paixão avassaladora. Enquanto isso, uma sinistra e antiga sombra avança sobre o mundo das fadas e Feyre deve provar seu amor para detê-la ou Tamlin e seu povo estarão condenados.</p>"
                break;
            
            case 1:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 640 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 658 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Neste livro, seguimos a saga de Feyre Archeron, que morreu Sob a Montanha. Nas garras de Amarantha, a jovem humana que ansiava por amor e proteção deixou de existir. Das cinzas de seu velho eu, Feyre Quebradora da Maldição foi Feita - com poderes de sete Grão-Feéricos... e uma vontade tão férrea quanto o metal temido por eles. Seu coração no entanto, permanece humano, vulnerável. Incapaz de esquecer o que sofreu para libertar o povo de Tamlin... e o pacto firmado com Rhysand, senhor da Corte Noturna. Mas mesmo assim, Feyre se esforça para reconstruir o lar que criou na Corte Primaveril.</p><p></p><p style='text-align: center;'>Então por que é ao lado de Rhys que ela se sente mais plena?</p><p>Peça-chave num jogo que desconhece, Feyre deve aprender rapidamente do que á capaz. E curar sua alma partida. Pois um antigo mal, muito pior que Amarantha, se agita no horizonte... um que ameaça não apenas os feéricos, mas o mundo humano e a muralha também. Enquanto navega por uma teia de intrigas políticas, paixões e poder, sufocada por Tamlin, Feyre precisa decidir o que deseja: amor ou liberdade?</p>"
                break;
            
            case 2:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 720 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 684 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Em meio à guerra, é seu coração que enfrentará a mais árdua das batalhas...</p><p>Seguindo os acontecimentos do volume anterior, Corte de Névoa e Fúria, acompanhamos a saga de Feyre Archeon, que suportou a fome, o frio e a desesperança, atravessou a Montanha e foi Sob a Montanha. Reclamou seu amor, quebrou a maldição e livrou o povo feérico da mais terrível ameaça... ou não? Amarantha pode ter sido aniquilada, mas o rei de Hybern pretende usar o Caldeirão para moldar um novo tempo; uma época de trevas e escravidão.</p><p>A guerra se aproxima, um conflito que promete devastar Prythian. Em meio à Corte Primaveril, num perigoso jogo de intrigas e mentiras, a Grã-Senhora da Corte Noturna esconde seu laço de parceria e sua verdadeira lealdade. Longe de sua corte, longe de seu Grão-Senhor e verdadeiro amor, ela reúne informações, na esperança de vencer Hybern. Tamlin está fazendo acordos com o invasor, Jurian recuperou suas forças e as rainhas humanas prometem se alinhar aos desejos de Hybern em troca de imortalidade. O exército inimigo parece imbatível. Mas o sonho de Velaris é como um farol em meio às trevas. O ideal de um mundo mais justo.</p><p>Enquanto isso Feyre e seus amigos precisam aprender em quais Grãos-Senhores confiar, e procurar aliados nos mais improváveis lugares. Porém, a Quebradora da Maldição ainda tem uma ou duas cartas na manga antes que sua ilha queime.</p>"
                break;
            
            case 3:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 272 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 238 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Às pessoas que olham para as estrelas e desejam.<br>Às estrelas que ouvem e aos sonhos que são atendidos.</p><p>Para Feyre Archeon, ser Grã-Senhora ainda é uma novidade, e ela precisa descobrir seu papel enquanto luta para reconstruir uma Velaris devastada pela guerra contra Hybern. A muralha que separava o mundo feérico do mundo humano se foi, Keir está prestes a deixar a Corte dos Pesadelos para uma visita à cidade de Luz Estelar e os illyrianos parecem insatisfeitos com o resultado da guerra.</p><p>Divididos entre as tentativas de retomar suas vidas após a grande batalha, as responsabilidades de liderar a Corte Noturna e a preparação para o rigoroso inverno, o trabalho de Feyre, Rhys e seu Círculo Íntimo parece nunca ter fim. Todos seguem tentando manter a paz, conquistada a base de muito esforço e perdas pessoais, após a queda da muralha. Mas com o Solstício de Inverno finalmente se aproximando, chega também a promessa de descanso conquistado com muito esforço.</p><p style='text-align: center;'>No entanto, nem as festividades conseguem impedir que as sombras da guerra se aproximem.</p><p>Enquanto vive o primeiro Solstício como Grã-Senhora, Feyre ainda lida com os horrores do passado recente e percebe que seu parceiro e sua família têm mais cicatrizes do que ela esperava - cicatrizes que podem impactar o futuro, e a paz, de sua Corte.</p> <p><strong>Corte de Gelo e Estrelas</strong> é um spin-off de Corte de Espinhos e Rosas, e tem como foco principal os seus personagens, proporcionando aos fãs da série, uma visão geral do universo após o final da primeira trilogia. Contado a partir de perspectivas alternadas, a narrativa permite que o leitor reencontre Feyre, Rhysand, Cassian, Morrigan, Elain, Nestha, Azriel e Amren, enquanto tentam encontrar o caminho para o novo mundo pós-guerra.</p>"
                break;

            case 4:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 768 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 714 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Nestha Archeron sempre foi orgulhosa, irritável e lenta em perdoar. Ter sido Feita pelo Caldeirão não tornou sua personalidade mais doce. Mas o que poucos sabem é que, por trás da fachada de força, Nestha carrega uma dor que a está corroendo: o arrependimento por não ter feito nada para ajudar a família quando caíram na pobreza e por não ter sido capaz de salvar o pai...</p><p>Desde que foi forçada a entrar no Caldeirão e se tornar Grã-Feérica contra sua vontade, ela lutou para encontrar um lugar para si mesma dentro do mundo estranho e mortal que habita. No entanto, ela não consegue superar os horrores da guerra com Hybern e tudo o que perdeu nela.A única pessoa que a incendeia, mais do que qualquer outra, é Cassian, o guerreiro com cicatrizes de batalha cuja posição na Corte Noturna de Rhysand e Feyre o mantém constantemente na órbita de Nestha.</p><p>Mas seu temperamento não é a única coisa que Cassian inflama. O fogo entre eles é inegável, e fica ainda mais quente quando são forçados a ficarem próximos um do outro.Como se não bastasse, a possibilidade de uma nova guerra desponta no horizonte e, enquanto isso, as traiçoeiras rainhas humanas que retornaram ao continente durante a última guerra forjaram uma perigosa nova aliança, ameaçando a frágil paz que se instalou nos reinos... E a chave para detê-los pode depender de Cassian e Nestha enfrentarem seu passado assustador.</p><p>Contra o pano de fundo arrebatador de um mundo devastado pela guerra e atormentado pela incerteza, Nestha e Cassian percebem que apenas juntos podem triunfar, e lutam contra monstros por dentro e por fora enquanto buscam aceitação – e cura – nos braços um do outro.</p>"
                break;
            
            case 5:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 406 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 392 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p><strong>A magia há muito abandonou Adarlan. Um perverso rei governa, punindo impiedosamente as minorias rebeldes. Mas tudo pode mudar quando uma assassina é chamada para o castelo. Em Trono de vidro, livro que da início a série bestseller com mais de um milhão de cópias vendidas e legiões de fãs no mundo todo, Celaena tem uma perigosa missão que pode lhe garantir sua tão sonhada liberdade ou ser a sua sentença de morte.</strong></p><p>Aos 18 anos uma prisioneira está cumprindo sua sentença. Ela é uma assassina, e a melhor de Adarlan. Aprisionada e fraca, ela está quase perdendo as esperanças, a sentença de morte é iminente, mas a jovem recebe uma proposta inesperada: representar o príncipe em uma competição com lutando contra os mais habilidosos assassinos e larápios do reino. Mas ela não diz sim apenas para matar, seu foco é obter sua liberdade de volta.</p><p>Se derrotar os 23 assassinos, ladrões e soldados, será a campeã do rei e estará livre depois de servi-lo por alguns anos.</p><p>Endovier é uma sentença de morte, e cada duelo em Adarlan será para viver ou morrer. Mas se o preço é ser livre, e ela está disposta a tudo.</p><p>Seu nome é Celaena Sardothien. O príncipe herdeiro vai provocá-la, o capitão da guarda fará tudo para protegê-la. E uma princesa de terras distantes se tornará algo que Celaena jamais pensou ter novamente: uma amiga.</p><p>Mas algo maligno habita o castelo - e está ali para matar. Quando os demais competidores começam a morrer, um a um e de maneira terrível, Celaena se vê mais uma vez envolvida em uma batalha pela sobrevivência e inicia uma jornada desesperada para desvendar a origem daquele mal antes que ele destrua o mundo dela. E sua única chance de ser livre.</p>"
                break;
            
            case 6:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 490 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 406 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Celaena Sardothien é a nova campeã do rei. Depois de vencer a brutal competição que a livrou da escravidão das Minas de Sal de Endovier, ela se tornou a assassina real. Coroa da meia noite é o segundo volume da série Trono de Vidro, onde acompanhamos a guerreira Celaena em busca do que mais deseja: sua liberdade.</p><p>Agora, a protagonista tem como obrigação é atravessar terra e mar em busca de inimigos do rei e fazer cumprir sua vontade. Como recompensa, recebe conforto, horas e mais horas de fartos banquetes, conselhos dados pela doce Nehemia e uma enorme quantia que lhe permite comprar luxuosos vestidos e muitos livros.</p><p>Embora tenha uma queda por luxos e vestidos bonitos, Celaena se apresenta como uma liderança forte e confiante, disposta a sacrificar tudo pela pessoa que ama, mas sem deixar que esse amor a defina de forma alguma. Pois sua lealdade está longe de pertencer ao trono de vidro.</p><p>Nos arredores do castelo, surgem rumores a respeito de uma conspiração contra os misteriosos planos do rei, e a assassina é encarregada de cuidar dos traidores. Quando descobre que sua próxima missão é matar um velho amigo, Celaena se vê em meio a uma perigosa trama de mentiras e traições tecida ao redor da coroa.</p><p>Para um reino onde há muito a magia foi extinta, Adarlan se revela um túmulo de segredos e mistérios, trancafiados atrás de cada porta, codificados nas páginas dos livros.</p><p>Enquanto Celaena tenta decifrar todos os enigmas e conviver com a eterna disputa entre seus protetores -príncipe Dorian e o capitão Westfall - uma trágica noite mudará a vida de todos no reino. Os muitos segredos enterrados sob o castelo de vidro começam a vir à tona, e Celaena mais do que nunca quer descobrir a verdade para fazer justiça.</p>"
                break;
            
            case 7:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 435 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 406 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Implacável. Sedutora. Letal. A Assassina de Adarlan é tudo isso.</p> <p><strong>Em A Lâmina da Assassina: Historias de Trono de Vidro conhecemos Celaena, sua fama ultrapassa os muros de Forte da Fenda, mais brilhante que as torres do castelo de vidro, onde o usurpador governa com mão de ferro o destino de todos em Erilea.</strong></p><p>Poucos conhecem seu rosto, menos ainda sobrevivem à sua fúria. Seu caminho rumo à fama estava escrito nas estrelas, sob a bênção da constelação do cervo branco, o Senhor do Norte, o mítico espírito de Terrasen.</p><p>Não à toa Celaena Sardothien é sinônimo de morte. Suas lâminas são certeiras. Assim como também o é seu estranho código de honra. Seu aguçado senso de justiça. Única, ela foi criada nas sarjetas. Mas como uma menina, encontrada agonizando pelo rei dos Assassinos de Adarlan, se tornaria a campeã do rei? Disputada pelo capitão da guarda real e pelo próprio príncipe herdeiro? No centro de intrigas políticas?</p><p>Conheça o caminho da assassina. Pavimentado com sangue, lágrimas e suor. Acompanhe Celaena vencer um Lorde Pirata e toda a sua tripulação; o encontro com uma Curandeira; seu treinamento com o Mestre Mudo, senhor dos assassinos silenciosos, nas dunas do Deserto Vermelho; a prisão nas Minas de Sal de Endovier; ou, ainda, sua luta contra o mais escorregadio e traiçoeiro dos adversários - o próprio coração.</p><p>O livro se desenvolve através de cinco histórias, que fluem diretamente uma para a outra e, juntas, contam a história dos eventos que levaram Celaena até onde ela está no começo de Trono de Vidro.</p>"
                break;
            
            case 8:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 576 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 518 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Chegou a hora de abraçar sua verdadeira herança e reivindicar a coroa de Terrasen. Agora é a vez do suor e das lágrimas, do sangue e do sacrifício. A justiça mais uma vez ocupará o trono do cervo branco, o Senhor do Norte. Presa ao juramento de sangue feito a Nehemia, Celaena procura a rainha feérica Maeve para aprender os segredos da própria magia. Enquanto treina com Rowan, um príncipe que leva a jovem aos limites da exaustão física e emocional. Mas infelizmente não há tempo para ceder às suas inseguranças, a hora para dúvidas é passada, pois Celaena descobre que uma batalha de proporções épicas se avizinha. Uma que pode escravizar a terra.</p><p>Em Forte da Fenda, o príncipe Dorian também tenta entender a magia, com o auxílio da curandeira Sorscha, que rapidamente se torna mais que amiga. Mas ela também guarda um segredo, que pode colocar o príncipe herdeiro em grave perigo. E ele não pode contar com o amigo Chaol, ocupado em descobrir mais sobre os rebeldes e o Lobo do Norte, Aedion, primo de Celaena.</p><p>Nas distantes montanhas Canino Branco, as bruxas do clã Dentes de Ferro treinam enormes serpentes aladas para os exércitos do rei. Em meio a esse cenário, Celaena se equilibra entre os vivos e os mortos, humanos e feéricos, enquanto seu mundo caminha para a guerra. Agora, a vitória depende de Celaena encontrar coragem para enfrentar tais perigos, além de seus próprios demônios, e fazer a escolha mais difícil da sua vida.</p>"
                break;

            case 9:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 672 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 644 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Todos que Celaena Sardothien amou lhe foram tirados. Mas finalmente chegou a hora da retribuição. A vingança promete ser tão dura quanto o aço da Espada de Orynth - a espada de seu pai. Finalmente Celaena retornou ao império; por justiça, para resgatar seu reino e confrontar as sombras do passado. A assassina está morta. Ela abraçou a identidade de Aelin Galathynius, Rainha de Terrasen. Mas antes de reivindicar o trono, ela precisa lutar. E ela vai lutar.</p><p>Por seu primo, o General do Norte... um guerreiro preparado para morrer por sua soberana; por seu amigo Dorian, um Príncipe preso em uma inimaginável prisão; por seu povo, escravizado por um Rei cruel e à espera do retorno triunfante de sua líder; por seu carranam e a libertação da magia.</p><p>Ao avançar em seu plano, no entanto, Aelin precisa tomar cuidado com velhos inimigos. E abrir o coração para novos e improváveis aliados. Tudo isso enquanto os valg continuam trabalhando nas sombras. E Manon Bico Negro, a Líder Alada das Treze, treina suas bestas voadoras. Mas é de Morath, a fortaleza montanhosa do Duque de Perrington, que uma ameaça como nenhuma outra promete destroçar seu grupo de rebeldes e sua corte recém-formada.</p>"
                break;

            case 10:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 672 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 644 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Chaol Westfall sempre se definiu por sua lealdade inquebrável, sua força e sua posição como capitão da Guarda. Mas tudo isso mudou desde que o Castelo de Vidro se quebrou; seus homens foram abatidos, e o rei de Adarlan o poupou de um golpe de morte, mas deixou seu corpo quebrado. Ele foi despedaçado emocionalmente, enlouquecendo pela culpa que sentia por decepcionar a si mesmo e a seus homens. Agora, enfraquecido se senta em uma cadeira, um recipiente para seu espírito profundamente combalido.</p><p>Sua única chance de recuperação reside nos lendários curandeiros da Torre Cesme em Antica - a fortaleza do poderoso império do continente do sul. E é para lá que ruma Chaol, acompanhado de Nesryn, a única mulher na Guarda Real e sua nova capitã, depois de ter sido nomeado Mão do Rei. Então, eles viajam para Antica, na esperança de que os lendários curandeiros da Torre Cesme curem seu corpo. Eles também esperam fazer aliados do império sul na iminente guerra.</p><p>Com a guerra se aproximando de Dorian e com Aelin lutando por seu trono de direito, Chaol pode ser uma peça-chave para a sobrevivência dos dois jovens monarcas, convencendo outros governantes a se aliarem a eles. O que Chaol e Nesryn descobrem em Antica, no entanto, vai mudar os dois - e será mais vital para salvar Erilea do que eles poderiam ter imaginado.</p>"
                break;

            case 11:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong> 695 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 364 (Tomo 1) - 322 (Tomo 2) <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Pelo Cervo, Senhor do Norte, ela será coroada. Mas o caminho até a coroa é longo e sinuoso. Lealdades serão corrompidas e laços, desfeitos; amigos serão perdidos e conquistados... e alianças inesperadas podem pender a balança na luta contra o Rei Sombrio. Com o coração preso ao príncipe feérico a seu lado, e a vida e o poder jurados ao povo que está determinada a salvar, a antiga assassina Celaena mergulhará no poço da própria magia, afim de proteger os seus. Para honrar a coroa de fogo sobre sua cabeça, Aelin colocará a própria segurança em risco.</p><p>Mas conforme monstros surgem de pesadelos do passado, do interior nefasto de Morath preparados a clamar o mundo, a única salvação está numa estranha relíquia, enterrada nas ruínas de um velho pântano. O Fecho é a chave para mandar o exército valg de volta à sua dimensão... O Rei Sombrio, Senhor do Medo, enviou seus Cães de Caça, os ilken, no encalço de seus inimigos. Mais que nunca, Aelin precisa de Rowan, de Dorian e de todos os aliados para conseguir descobrir a relíquia sagrada capaz de banir de seu mundo a ameaça valg e os horrores libertados em Morath.</p><p>A tarefa não é fácil. Mas a herdeira de Mala tem alguns truques na manga... Algo ainda mais poderoso que as chaves de Wyrd. Algo maior que o Fecho: a própria astúcia e a fé inabalável em um mundo melhor. Algo que encanta até mesmo Manon Bico Negro e sua Ceifadora do Vento. Com a ajuda de sua corte, da esperança de um recomeço, Aelin precisará escolher o que - e a quem - está disposta a sacrificar para assegurar o futuro de toda Erilea.</p><p>Com a bruxa ao seu lado, ela talvez tenha uma chance. Chegou a hora de levantar os exércitos de Erilea. De cobrar velhas dívidas... É hora de marchar contra o mais supremo dos males. E confiar na pureza de seu coração para trazer a luz. Mas será o suficiente?</p>"
                break;

            case 12:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Sarah J. Maas</li><li><strong>Nº de Páginas:</strong>  <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'>  <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Uma princesa que viveria por mil anos. Deveria ser uma dádiva, mas agora é uma maldição.</p><p>Aelin arriscou tudo para salvar seu povo, mas isso pode não ter sido suficiente. Capturada pela rainha sombria trancada em um caixão de ferro, Aelin luta para permanecer forte e resistir às torturas de Maeve, pois sabe que a sobrevivência de seu povo depende disso.</p><p>Embora tenha resistido por vários meses, sua determinação começa a diminuir a cada dia que passa. Em Terrasen, Aedion, Lysandra e seus aliados se esforçam para conter a ameaça iminente, porém a força dessa aliança pode não ser o suficiente para barrar as hordas de Erawan e proteger Terrasen da destruição total.</p><p>Espalhados pelo continente, Chaol, Manon e Dorian precisam correr contra o tempo para encontrar seus destinos. Toda esperança de salvação - e de um mundo melhor - encontra-se por um fio. E do outro lado do oceano, com seus companheiros inabaláveis, Rowan luta para encontrar sua parceira e rainha capturada - antes que a perca para sempre.</p><p>A batalha final se aproxima, todos devem se reunir em Terrasen, para uma última tentativa de vencer a guerra contra Maeve, Erwan e Valg. Seus finais felizes estão à vista se eles puderem aguentar o tempo suficiente para alcançá-los.</p>"
                break;

            case 13:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tahereh Mafi</li><li><strong>Nº de Páginas:</strong> 338 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 304 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Distopia, Fantasia, Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>Juliette nunca se sentiu como uma pessoa normal. Nunca foi como as outras meninas de sua idade. O motivo: ela não podia tocar ninguém. Seu toque era capaz de ferir e até matar. Durante anos, Juliette feriu e, segundo seus pais, arruinou o que estava à sua volta com um simples toque, o que a levou a ser presa numa cela. Todo dia era escuro e igual para Juliette até a chegada de um companheiro de cela, Adam.</p><p>Dentro do cubículo escuro, Juliette não tinha notícias do mundo lá fora. Adam ia atualizando-a de tudo. Juliette não entendeu bem o que estava acontecendo quando foi retirada daquela cela e supostamente libertada, ao lado de Adam, e se vê em uma encruzilhada, com a possibilidade de retomar sua vida, mas por caminhos tortuosos e totalmente desconhecidos.</p>"
                break;

            case 14:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tahereh Mafi</li><li><strong>Nº de Páginas:</strong> 461 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 448 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Distopia, Fantasia, Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>Após escapar do Restabelecimento e encontrar a sede da resistência rebelde – um lugar para pessoas com dons, como ela –, Juliette enfim se sente livre… livre do plano de ser usada como arma e livre para amar. Mas ela nunca estará livre de seu toque letal. Nem da guerra que se aproxima.</p><p>Assombrada pelo passado e aterrorizada com o futuro, ela sabe que precisa tomar decisões capazes de mudar sua vida, entre o que quer e o que acredita ser correto. Decisões que podem envolver escolhas entre seu coração e a vida de alguém.</p>"
                break;

            case 15:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tahereh Mafi</li><li><strong>Nº de Páginas:</strong> 421 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 384 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Distopia, Fantasia, Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>O destino do Ponto Ômega é desconhecido. Todas as pessoas com quem Juliette se importa podem estar mortas. Talvez a guerra tenha chegado ao fim antes mesmo de ter começado. Juliette foi a única que restou no caminho d O Restabelecimento. E sabe que, se ela sobreviver, O Restabelecimento não sobreviverá.</p><p>Entretanto, para destruir O Restabelecimento e o homem que quase a matou, Juliette vai precisar da ajuda de alguém em quem nunca pensou que pudesse confiar: Warner. Enquanto eles lutam juntos para combater o inimigo, Juliette descobre que tudo que ela pensava saber sobre seu poder, sobre Warner e até mesmo Adam era uma mentira.</p>"
                break;

            case 16:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tahereh Mafi</li><li><strong>Nº de Páginas:</strong> 435 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 352 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Distopia, Fantasia, Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>A história de Juliette e Warner continua no eletrizante novo volume da série Estilhaça-me, de Tahereh Mafi, autora best-seller do The New York Times.</p><p>Juliette Ferrars acreditava ter vencido. Assumiu o controle do Setor 45, foi nomeada nova Comandante Suprema da América do Norte e agora conta com Warner ao seu lado. No entanto, quando a tragédia se instala, Juliette precisa confrontar a escuridão que existe tanto à sua volta quanto em seu interior.</p><p>Em que ela se transformará diante da adversidade? Será Juliette capaz de controlar seu poder e usá-lo para o bem?</p>"
                break;

            case 17:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tahereh Mafi</li><li><strong>Nº de Páginas:</strong> 357 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 304 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Distopia, Fantasia, Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>O curto mandato de Juliette como comandante suprema da América do Norte foi um desastre total. Quando os filhos dos outros líderes mundiais aparecem à sua porta, tudo o que ela quer é recorrer a Warner para obter apoio e orientação. Mas ele parte seu coração ao revelar que está mantendo segredos sobre a família e a identidade dela – segredos esses que mudam tudo.</p><p>Em Desafia-me, Juliette descobre que nada em seu mundo é o que parece. Ela achava que tinha derrotado o Restabelecimento, que finalmente assumiria o controle de sua vida, de seu poder, de sua dor. Mas ver uma vida inteira de mentiras se desfazendo diante de si muda tudo. Agora, Juliette deve lutar pela vida e pelo amor, mas primeiro terá de sobreviver à guerra sendo travada contra a sua mente: ela terá de lembrar quem ela mesma era.</p>"
                break;
                
            case 18:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tahereh Mafi</li><li><strong>Nº de Páginas:</strong> 450 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 366 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Distopia, Fantasia, Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>Agora que Ella sabe quem é Juliette e para qual finalidade foi criada, as coisas só se tornaram mais complicadas. Enquanto ela luta para entender o passado que a assombra e contempla um futuro mais incerto do que nunca, os limites entre certo e errado – entre Ella e Juliette – não estão tão evidentes. E, com velhos inimigos se aproximando, seu destino pode não estar sob seu próprio controle.</p><p>O dia do acerto de contas para o Restabelecimento está chegando. Mas será que ela conseguirá escolher de que lado lutará?</p>"
                break;

            case 19:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Holly Black</li><li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 322 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p>Jude tinha apenas sete anos quando seus pais foram brutalmente assasinados e ela e as irmãs levadas para viver no traiçoeiro Reino das Fadas. Dez anos depois, tudo o que Jude quer é se encaixar, mesmo sendo uma garota mortal. Mas todos os feéricos parecem desprezar os humanos... Especialmente o príncipe Cardan, o mais jovem e mais perverso dos filhos do Grande Rei de Elfhame.</p><p>Para conquistar o tão desejado lugar na Corte, Jude precisa desafiar o príncipe - e enfrentar as consequências do ato. A garota passa, então, a se envolver cada vez mais nos jogos e intrigas do palácio, e acaba descobrindo a própria vocação para trapaças e derramamento de sangue. Mas quando uma traição ameaça afogar o Reindo das Fadas em violência, Jude precisará arriscar tudo em uma perigosa aliança para salvar suas irmãs - e a própria Elfhame.</p><p>Cercada por mentiras e pessoas que desejam destruí-la, Jude terá que descobrir o verdadeiro significado da palavra poder antes que seja tarde demais.</p>"
                break;
            
            case 20:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Holly Black</li><li><strong>Nº de Páginas:</strong> 336 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 308 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Fantasia, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Você precisa ser forte o suficiente para golpear e golpear de novo sem se cansar.<br>Vai doer. Mas a dor fortalece.</p><p>Para sobreviver no Reino das Fadas, Jude Duarte precisou aprender muitas lições. A mais importante delas veio de seu padrasto: <em>o poder é bem mais fácil de adquirir do que de manter</em>. Ela achou que, depois de enganar Cardan para que ele jurasse obedecê-la por um ano e um dia, sua vida se tornaria mais fácil.</p><p>Agora, Cardan é o Grande Rei. Jude é a mão por trás do trono. Cinco meses já se passaram, e ela não conseguiu fazer nada além de dar algumas ordens banais ao Rei. Se quiser guardar o trono para seu irmão, Jude precisará pensar, e rápido, num plano para fazer Cardan se curvar a ela por mais tempo. Mas ter qualquer influência sobre o Grande Rei de Elfhame parece uma tarefa impossível, principalmente quando ele faz de tudo em seu poder para humilhá-la e prejudicá-la, mesmo que seu fascínio pela garota humana permaneça intacto.</p><p>Como se não bastasse, as ondas ameaçam engolir as ilhas de Elfhame e Jude recebe um alerta: alguém traiu você. Mas quem? Jude precisa lutar para salvar a própria vida e a daqueles que ama, além de lutar contra seus sentimentos conflituosos por Cardan. Em um mundo imortal, um ano e um dia não são nada...</p>"
                break;
            
            case 21:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Holly Black</li><li><strong>Nº de Páginas:</strong> 320 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 294 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Ficção Fantástica, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Ele será a destruição da coroa e a ruína do trono.</p><p>O poder é mais fácil de adquirir do que de manter. Jude aprendeu a lição mais difícil de sua vida quando abdicou do controle do Rei Cardan em troca de um poder imensurável.</p><p>Agora, ela carrega o outrora impensável título de Grande Rainha de Elfhame, mas as condições são longe de ser ideais. Exilada por Cardan no mundo mortal, Jude se encontra impotente e frustrada enquanto planeja reivindicar tudo que Cardan tomou dela.</p><p>A oportunidade surge com sua irmã gêmea, cuja vida está em perigo. Para salvá-la de uma situação tenebrosa envolvendo Locke, Jude decide voltar ao Reino das Fadas se passando por Taryn. Antes disso, porém, ela precisa confrontar os próprios sentimentos contraditórios pelo rei que a traiu.</p><p>No entanto, ao voltar a Elfhame, Jude constata que tudo mudou. A guerra está prestes a eclodir, e ela caminha próximo a seus inimigos. Será que ela vai ser capaz de resgatar a Coroa e o amor incondicional de Cardan, ao mesmo tempo que destrói os planos de seus inimigos? Ou será que tudo está perdido para sempre?</p>"
                break;

            case 22:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 288 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>Simon Basset, o irresistível duque de Hastings, acaba de retornar a Londres depois de seis anos viajando pelo mundo. Rico, bonito e solteiro, ele é um prato cheio para as mães da alta sociedade, que só pensam em arrumar um bom partido para suas filhas. Simon, porém, tem o firme propósito de nunca se casar. Assim, para se livrar das garras dessas mulheres, precisa de um plano infalível.</p><p>É quando entra em cena Daphne Bridgerton, a irmã mais nova de seu melhor amigo. Apesar de espirituosa e dona de uma personalidade marcante, todos os homens que se interessam por ela são velhos demais, pouco inteligentes ou destituídos de qualquer tipo de charme. E os que têm potencial para ser bons maridos só a veem como uma boa amiga.</p><p>A ideia de Simon é fingir que a corteja. Dessa forma, de uma tacada só, ele conseguirá afastar as jovens obcecadas por um marido e atrairá vários pretendentes para Daphne. Afinal, se um duque está interessado nela, a jovem deve ter mais atrativos do que aparenta.</p><p>Mas, à medida que a farsa dos dois se desenrola, o sorriso malicioso e os olhos cheios de desejo de Simon tornam cada vez mais difícil para Daphne lembrar que tudo não passa de fingimento. Agora, ela precisa fazer o impossível para não se apaixonar por esse conquistador inveterado que tem aversão a tudo o que ela mais quer na vida.</p>"
                break;

            case 23:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 354 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 304 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>A temporada de bailes e festas de 1814 acaba de começar em Londres. Como de costume, as mães ambiciosas já estão ávidas por encontrar um marido adequado para suas filhas. Ao que tudo indica, o solteiro mais cobiçado do ano será Anthony Bridgerton, um visconde charmoso, elegante e muito rico que, contrariando as probabilidades, resolve dar um basta na rotina de libertino e arranjar uma noiva.</p><p>Ele logo decide que Edwina Sheffield, a debutante mais linda da estação, é a candidata ideal. Mas, para levá-la ao altar, primeiro terá que convencer Kate, a irmã mais velha da jovem, de que merece se casar com ela.</p><p>Não será uma tarefa fácil, porque Kate não acredita que ex-libertinos possam se transformar em bons maridos e não deixará Edwina cair nas garras dele.</p><p>Enquanto faz de tudo para afastá-lo da irmã, Kate descobre que o visconde devasso é também um homem honesto e gentil. Ao mesmo tempo, Anthony começa a sonhar com ela, apesar de achá-la a criatura mais intrometida e irritante que já pisou nos salões de Londres. Aos poucos, os dois percebem que essa centelha de desejo pode ser mais do que uma simples atração.</p>"
                break;

            case 24:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 304 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>Sophie sempre quis ir a um evento da sociedade londrina. Mas esse parece um sonho impossível. Apesar de ser filha de um conde, ela é fruto de uma relação ilegítima e foi relegada ao papel de criada pela madrasta assim que o pai morreu.</p><p>Uma noite, porém, ela consegue entrar às escondidas no aguardado baile de máscaras de Lady Bridgerton. Lá, conhece o charmoso Benedict, filho da anfitriã, e se sente parte da realeza. No mesmo instante, uma faísca se acende entre eles.</p><p>Infelizmente, o encantamento tem hora para acabar. À meia-noite, Sophie tem que sair correndo da festa e não revela sua identidade a Benedict. No dia seguinte, enquanto ele procura sua dama misteriosa por toda a cidade, Sophie é expulsa de casa pela madrasta e precisa deixar Londres.</p><p>O destino faz com que os dois só se reencontrem três anos depois. Benedict a salva das garras de um bêbado violento, mas, para decepção de Sophie, não a reconhece nos trajes de criada. No entanto, logo se apaixona por ela de novo. Como é inaceitável que um homem de sua posição se case com uma serviçal, ele lhe propõe que seja sua amante, o que para Sophie é inconcebível.</p><p>Agora os dois precisarão lutar contra o que sentem um pelo outro ou reconsiderar as próprias crenças para terem a chance de viver um amor de conto de fadas.</p>"
                break;

            case 25:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li><li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 336 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>" 

                sinopse.innerHTML = "<p>Há muitos anos Penélope Featherington frequenta a casa dos Bridgertons. E há muitos anos alimenta uma paixão secreta por Colin, irmão de sua melhor amiga e um dos solteiros mais encantadores e arredios de Londres.</p><p>Quando ele retorna de uma de suas longas viagens ao exterior, Penélope descobre seu maior segredo por acaso e chega à conclusão de que tudo o que pensava sobre seu objeto de desejo talvez não seja verdade. Ele, por sua vez, também tem uma surpresa: Penélope se transformou, de uma jovem sem graça ignorada por toda a alta sociedade, numa mulher dona de um senso de humor afiado e de uma beleza incomum.</p><p>Ao deparar com tamanha mudança, Colin, que sempre a enxergara apenas como uma divertida companhia ocasional, começa a querer passar cada vez mais tempo a seu lado. Quando os dois trocam o primeiro beijo, ele não entende como nunca pôde ver o que sempre esteve bem à sua frente.</p><p>No entanto, quando fica sabendo que ela guarda um segredo ainda maior que o seu, precisa decidir se Penélope é sua maior ameaça ou a promessa de um final feliz.</p>"
                break;

            case 26:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 372 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 288 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>Eloise Bridgerton é uma jovem simpática e extrovertida, cuja forma preferida de comunicação sempre foram as cartas, nas quais sua personalidade se torna ainda mais cativante. Quando uma prima distante morre, ela decide escrever para o viúvo e oferecer as condolências. Ao ser surpreendido por um gesto tão amável vindo de uma desconhecida, Sir Phillip resolve retribuir a atenção e responder.</p><p>Assim, os dois começam uma instigante troca de correspondências. Ele logo descobre que Eloise, além de uma solteirona que nunca encontrou o par perfeito, é uma confidente de rara inteligência. E ela fica sabendo que Sir Phillip é um cavalheiro honrado que quer encontrar uma esposa para ajudá-lo na criação de seus dois filhos órfãos.</p><p>Após alguns meses, uma das cartas traz uma proposta peculiar: o que Eloise acharia de passar uma temporada com Sir Phillip para os dois se conhecerem melhor e, caso se deem bem, pensarem em se casar? Ela aceita o convite, mas em pouco tempo eles se dão conta de que, ao vivo, não são bem como imaginaram. Ela é voluntariosa e não para de falar, e ele é temperamental e rude, com um comportamento bem diferente dos homens da alta sociedade londrina.</p><p>Apesar disso, nos raros momentos em que Eloise fecha a boca, Phillip só pensa em beijá-la. E cada vez que ele sorri, o resto do mundo desaparece e ela só quer se jogar em seus braços. Agora os dois precisam descobrir se, mesmo com todas as suas imperfeições, foram feitos um para o outro.</p>"
                break;
            
            case 27:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 368 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 304 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>Toda vida tem um divisor de águas, um momento súbito, empolgante e extraordinário que muda a pessoa para sempre. Para Michael Stirling, esse instante ocorreu na primeira vez em que pôs os olhos em Francesca Bridgerton.</p><p>Depois de anos colecionando conquistas amorosas sem nunca entregar seu coração, o libertino mais famoso de Londres enfim se apaixonou. Infelizmente, conheceu a mulher de seus sonhos no jantar de ensaio do casamento dela. Em 36 horas, Francesca se tornaria esposa do primo dele.</p><p>Mas isso foi no passado. Quatro anos depois, Francesca está livre, embora só pense em Michael como amigo e confidente. E ele não ousa falar com ela sobre seus sentimentos – a culpa por amar a viúva de John, praticamente um irmão para ele, não permite.</p><p>Em um encontro inesperado, porém, Francesca começa a ver Michael de outro modo. Quando ela cai nos braços dele, a paixão e o desejo provam ser mais fortes do que a culpa. Agora o ex-devasso precisa convencê-la de que nenhum homem além dele a fará mais feliz.</p>"
                break;

            case 28:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 272 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>Toda a alta sociedade concorda que não existe ninguém parecido com Hyacinth Bridgerton. Cruelmente inteligente e inesperadamente franca, ela já está em sua quarta temporada na vida social da elite, mas não consegue se impressionar com nenhum pretendente.</p><p>Num recital, Hyacinth conhece o belo e atraente Gareth St. Clair, neto de sua amiga Lady Danbury. Para sua surpresa, apesar da fama de libertino, ele é capaz de manter uma conversa adequada com ela e, às vezes, até deixá-la sem fala e com um frio na barriga.</p><p>Porém Hyacinth resiste à sedução do famoso conquistador. Para ela, cada palavra pronunciada por Gareth é um desafio que deve ser respondido à altura. Por isso, quando ele aparece na casa de Lady Danbury com um misterioso diário da avó italiana, ela resolve traduzir o texto, que pode conter segredos decisivos para o futuro dele.</p><p>Nessa tarefa, primeiro os dois se veem debatendo traduções, depois trocando confidências, até, por fim, quebrarem as regras sociais. E, ao passar o tempo juntos, eles vão descobrir que as respostas que buscam se encontram um no outro... e que não há nada de tão simples – e de tão complicado – quanto um beijo.</p>"
                break;

            case 29:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 371 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 320 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p>Ao contrário da maioria de seus amigos, Gregory Bridgerton sempre acreditou no amor. Não podia ser diferente: seus pais se adoravam e seus sete irmãos se casaram apaixonados. Por isso, o jovem tem certeza de que também encontrará a mulher que foi feita para ele e que a reconhecerá assim que a vir. E é exatamente isso que acontece.</p><p>O problema é que Hermione Watson está encantada por outro homem e não lhe dá a menor atenção. Para sorte de Gregory, porém, Lucinda Abernathy considera o pretendente da melhor amiga um péssimo partido e se oferece para ajudar o romântico Bridgerton a conquistá-la.</p><p>Mas tudo começa a mudar quando quem se apaixona por ele é Lucy, que já foi prometida pelo tio a um homem que mal conhece. Agora, será que Gregory perceberá a tempo que ela, com seu humor inteligente e seu sorriso luminoso, é a mulher ideal para ele?</p>"
                break;

            case 30:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Julia Quinn</li> <li><strong>Nº de Páginas:</strong> 374 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 256 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Ficção histórica</li>"

                sinopse.innerHTML = "<p class='frase'>Alguns finais são apenas o começo... Era uma vez uma família criada por uma autora de romances históricos...</p><p>Mas não era uma família comum. Oito irmãos e irmãs, seus maridos e esposas, filhos e filhas, sobrinhas e sobrinhos, além de uma irresistível matriarca. Esses são os Bridgertons: mais que uma família, uma força da natureza.</p><p>Ao longo de oito romances que foram sucesso de vendas, os leitores riram, choraram e se apaixonaram. Só que eles queriam mais. Então começaram a questionar a autora: O que aconteceu depois? Simon leu as cartas deixadas pelo pai? Francesca e Michael tiveram filhos? O que foi feito dos terríveis enteados de Eloise? Hyacinth finalmente encontrou os diamantes?</p><p style='text-align: center;'>A última página de um livro realmente tem que ser o fim da história?</p><p>Julia Quinn acha que não e, em E viveram felizes para sempre , oferece oito epílogos extras, todos sensuais, engraçados e reconfortantes, e responde aos anseios dos leitores trazendo, ainda, um drama inesperado, um final feliz para um personagem muito merecedor e um delicioso conto no qual ficamos conhecendo melhor ninguém menos que a sábia e espirituosa matriarca Violet Bridgerton.</p><p>Veja como tudo começou e descubra o que veio depois do fim desta série que encantou leitores no mundo inteiro.</p>"
                break;

            case 31:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Casey McQuiston</li><li><strong>Nº de Páginas:</strong> 421 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 392 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance, Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>O que pode acontecer quando o filho da presidenta dos Estados Unidos se apaixona pelo príncipe da Inglaterra?</p><p>Quando sua mãe foi eleita presidenta dos Estados Unidos, Alex Claremont-Diaz se tornou o novo queridinho da mídia norte-americana. Bonito, carismático e com personalidade forte, Alex tem tudo para seguir os passos de seus pais e conquistar uma carreira na política, como tanto deseja.</p><p>Mas quando sua família é convidada para o casamento real do príncipe britânico Philip, Alex tem que encarar o seu primeiro desafio diplomático: lidar com Henry, irmão mais novo de Philip, o príncipe mais adorado do mundo, com quem ele é constantemente comparado ― e que ele não suporta.</p><p>O encontro entre os dois sai pior do que o esperado, e no dia seguinte todos os jornais do mundo estampam fotos de Alex e Henry caídos em cima do bolo real, insinuando uma briga séria entre os dois. Para evitar um desastre diplomático, eles passam um fim de semana fingindo ser melhores amigos e não demora para que essa relação evolua para algo que nenhum dos dois poderia imaginar ― e que não tem nenhuma chance de dar certo. Ou tem?</p>"
                break;

            case 32:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Elle Kennedy</li> <li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 296 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance e Young Adult</li>"

                sinopse.innerHTML = "<p>De todos os jogadores do time de Hóquei da universidade de Briar, John Tucker se destaca por ser o mais sensato, gentil e amável. Diferente de seus amigos mulherengos, ele sonha mesmo é com uma vida tranquila: esposa, filhos e, quem sabe um dia, abrir um negócio próprio. Mas nem mesmo o cara mais calmo do mundo estaria preparado para o turbilhão de emoções que ele está prestes a enfrentar.</p><p>Sabrina James é a pessoa mais ambiciosa, dedicada e batalhadora do campus. Seu jeito sério e objetivo é interpretado por muitos como frieza, mas ela não está nem aí para sua fama de antipática. Tudo o que ela quer é passar em Harvard, tirar ótimas notas e conquistar a tão sonhada carreira como advogada. Só assim ela conseguirá escapar de seu passado difícil e de sua família terrível. Um acontecimento inesperado vai desses jovens de cabeça para baixo.</p><p>Tucker e Sabrina vão precisar se unir e rever seus planos para o futuro. Juntos, eles aprenderão que a vida é cheia de surpresas, e que o amor é a maior conquista de todas.</p>"
                break;

            case 33:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tessa Dare</li><li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 288 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance e Ficção Histórica</li>"

                sinopse.innerHTML = "<p>O que pode acontecer quando um canalha decide acompanhar uma mulher inteligente em uma viagem? A bela e inteligente geóloga Minerva Highwood, uma das solteiras convictas de Spindle Cove, precisa ir à Escócia para apresentar uma grande descoberta em um importante simpósio. Mas para que isso aconteça, ela precisará encontrar alguém que a leve.</p><p>Colin Sandhurst Payne, o Lorde Payne, um libertino de primeira, quer estar em qualquer lugar – menos em Spindle Cove. Minerva decide, então, que ele é a pessoa ideal para embarcar com ela em sua aventura. Mas como uma mulher solteira poderia viajar acompanhada por um homem sem reputação?</p><p>Esses parceiros improváveis têm uma semana para convencer suas famílias de que estão apaixonados, forjar uma fuga, correr de bandidos armados, sobreviver aos seus piores pesadelos e viajar 400 milhas sem se matar. Tudo isso dividindo uma pequena carruagem de dia e compartilhando uma cama menor ainda à noite.</p><p>Mas durante essa conturbada convivência, Colin revela um caráter muito mais profundo que seu exterior jovial, e Minerva prova que a concha em que vive esconde uma bela e brilhante alma. Talvez uma semana seja tempo suficiente para encontrarem um mundo de problemas. Ou, quem sabe, um amor eterno.</p>"
                break;

            case 34:
                informacoes.innerHTML = "<li><strong>Autor:</strong> Rick Riordan</li><li><strong>Nº de Páginas:</strong> 384 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 400 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Fantasia, Aventura, Mitologia Grega</li>"

                sinopse.innerHTML = "<p>O autor conjuga lendas da mitologia grega com aventuras no século XXI. Nelas, os deuses do Olimpo continuam vivos, ainda se apaixonam por mortais e geram filhos metade deuses, metade humanos, como os heróis da Grécia antiga. Marcados pelo destino, eles dificilmente passam da adolescência. Poucos conseguem descobrir sua identidade.</p><p>O garoto-problema Percy Jackson é um deles. Tem experiências estranhas em que deuses e monstros mitológicos parecem saltar das páginas dos livros direto para a sua vida. Pior que isso: algumas dessas criaturas estão bastante irritadas. Um artefato precioso foi roubado do Monte Olimpo e Percy é o principal suspeito. Para restaurar a paz, ele e seus amigos – jovens heróis modernos – terão de fazer mais do que capturar o verdadeiro ladrão: precisam elucidar uma traição mais ameaçadora que fúria dos deuses.</p>"
                break;

            case 35:
                informacoes.innerHTML = "<li><strong>Autora:</strong> Tillie Cole</li><li><strong>Nº de Páginas:</strong> 352 <img src='./src/imgs/bandeira-estados-unidos.png' alt='Bandeira do Estados Unidos'> 400 <img src='./src/imgs/bandeira-brasil.png' alt='Bandeira do Brasil'></li><li><strong>Gênero Literário:</strong> Romance e Young Adult</li>"

                sinopse.innerHTML = "<p class='frase'>Um beijo dura um instante. Mas mil beijos podem durar uma vida inteira.<br>Um garoto. Uma garota.<br>Um vínculo que é definido num momento e se prolonga por uma década. Um vínculo que nem o tempo nem a distância podem romper.<br>Um vínculo que vai durar para sempre.</p><p>Ao menos era o que eles imaginavam. Quando, aos dezessete anos, Rune Kristiansen retorna da Noruega para o lugar onde passou a infância, a cidade americana de Blossom Grove, na Geórgia , ele só tem uma coisa em mente: reencontrar Poppy Litchfield, a garota que era sua cara-metade e que tinha prometido esperar fielmente por seu retorno. E ele quer descobrir por que, nos dois anos em que esteve fora, ela o deletou de sua vida sem dar nenhuma explicação.</p>"
                break;

            default:
                break;
        }
    })
})